defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: 8b171ee8559cde7c8696b5459b49e19cb8ec2cdf942a6a64107706c803f5f1b9b96ae7378a32240ce5119807ac7cf12cd8dd32313188d2f72a3452d28e9c3e44
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v2.0.1/index.cjs'

yarnPath: .yarn/releases/yarn-4.3.0.cjs
