defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 5d

plugins:
  - checksum: cabb749817fc7efb69ded708ec63b822668802008e842b3541bca688ebcf271379334a176f4e235152eac201c726b886c5ccbef39d4ebe7ac09e94aeddabc5e1
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v2.0.4/index.cjs'

yarnPath: .yarn/releases/yarn-4.11.0.cjs
