defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 5d

npmPreapprovedPackages:
  - '@willbooster/babel-configs'
  - '@willbooster/biome-config'
  - '@willbooster/eslint-config-js'
  - '@willbooster/eslint-config-js-react'
  - '@willbooster/eslint-config-next'
  - '@willbooster/eslint-config-ts'
  - '@willbooster/eslint-config-ts-react'
  - '@willbooster/prettier-config'
  - '@willbooster/wb'
  - next
  - '@next/*'
  - react
  - react-dom

plugins:
  - checksum: d387bf474c315e463ddcbda77aabda9ba0b28ab3723fccccf40a310a3225d073963841bc255b2d2d8de9c1111548a7308b6af27eb31db57c75c4b9cb05aea73e
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v2.0.7/index.cjs'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
