defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - checksum: 589efe94b0c69c0c43c5b022915c8d2f0b12808a2028a993a1185c18cdf91a0278e7f3d1150136aaeb93f204170caeb3f7ebef62083b784ee97676086b941072
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.8.1/index.cjs'

yarnPath: .yarn/releases/yarn-4.0.0-rc.32.cjs
