nodeLinker: node-modules
defaultSemverRangePrefix: ''

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.0-rc.8.cjs
