defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 5d

npmPreapprovedPackages:
  - '@willbooster/babel-configs'
  - '@willbooster/biome-config'
  - '@willbooster/eslint-config-js'
  - '@willbooster/eslint-config-js-react'
  - '@willbooster/eslint-config-next'
  - '@willbooster/eslint-config-ts'
  - '@willbooster/eslint-config-ts-react'
  - '@willbooster/prettier-config'
  - '@willbooster/wb'

plugins:
  - checksum: 10d1f66930bd41d82eccee876d123cc379afafb9dece6960700240d6034c4dd2e4a72300600c4b3f094f7a062d1e6f397dd97a2168e0db372e33a78be7fa4591
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v2.0.6/index.cjs'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
