name: Add issue to github project
on:
  issues:
    types:
      - labeled
jobs:
  add-to-project:
    uses: WillBooster/reusable-workflows/.github/workflows/add-issue-to-project.yml@main
    secrets:
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      GH_PROJECT_URL: ${{ secrets.GH_PROJECT_URL }}
