name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  release:
    uses: WillBooster/reusable-workflows/.github/workflows/release.yml@main
    with:
      github_hosted_runner: true
    secrets:
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
