name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    uses: WillBooster/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
