name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    uses: WillBooster/reusable-workflows/.github/workflows/release.yml@main
    with:
      non_self_hosted: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
